### ISSUE TITLE
OnlineInvoiceTool_installer_2021_01_04.exe  használata

### ISSUE THREAD

**Issue by PeterAdam** [nav-gov-hu/Online-Invoice-Test-Tool#1]
A program telepítése során nem hozza létre a C:\Program Files (x86)\Online Invoice Test Tool\apixsd mappát, nem telepít xsd-ket. A megjelenő ablak információjával szemben nem hozza létre a c:\temp\invoice mappát az xml-eknek.

Indításakor hibák:
2021.01.06 09:09:42:0003 Invoice data path C:\Program Files (x86)\Online Invoice Test Tool\invoicesamples doesn't exists!
2021.01.06 09:09:42:0073 .dirindex file doesn't exist!
2021.01.06 09:09:42:0143 Invoice Data path not found! Nem található a következő elérési út egy része.: „C:\Program Files (x86)\Online Invoice Test Tool\invoicesamples\.dirindex”.

A letöltött xsd-ket megadva neki, src-resolve: Cannot resolve the name 'common:AtomicStringType255' to a(n) 'type definition' component. Tehát nem úgy tűnik, hogy értelmezné a common sémát.

Mit mondjunk a külföldi fejlesztőnek, hogy validáljon?

**Comment by renced42** [comment]
Kedves @PeterAdam 

Megyek sorba :) 

"A program telepítése során nem hozza létre a C:\Program Files (x86)\Online Invoice Test Tool\apixsd mappát, nem telepít xsd-ket."

Valóban, korábban a telepítő tartalmazta az XSD-ket, de mivel ezek változnak és kint vannak a Github-on nincs értelme párhuzamosan verziózni őket, mert akkor nekem is állandóan figyelni kell a változásokat. (Új feature-ként beteszem, hogy töltse le a legfrisebbet) Ezeket a fejlesztőnek kell letölteni 
Innen: https://github.com/nav-gov-hu/Online-Invoice és innen https://github.com/nav-gov-hu/Common

 "A megjelenő ablak információjával szemben nem hozza létre a c:\temp\invoice mappát az xml-eknek."
A leírás alapján itt neked kell megadni azt a mappát amiben a számla XML-ek vannak. A kitöltés csak példa.
Ezt egyébként meg lehet változtatni a Sequence Editor fülön. Bővebben a kézikönyv szerint.

![image](https://user-images.githubusercontent.com/44041065/103747780-73a13200-5003-11eb-9049-5a0d8826b004.png)


"Indításakor hibák:"
Ezek a hibák induláskor normálisak, hiszen nincs még semmi beállítva, bekonfigurálva.
Viszont itt egy régi hiba derült ki, ugyanis a telepítőben elméletileg azért kell megadni az elején egy mappát, hogy azt olvassa fel a program az indulásakor, ne pedig egy másikat. Ezt javítani kell. A Sequence Editorban ha kitallóztál egy mappát és a mentés ikonra klikkelsz akkor létrehozza a .dirindex fájlt.

"A letöltött xsd-ket megadva neki, src-resolve: Cannot resolve the name 'common:AtomicStringType255' to a(n) 'type definition' component. Tehát nem úgy tűnik, hogy értelmezné a common sémát."

Erre itt találsz választ: https://github.com/nav-gov-hu/Online-Invoice/issues/556

**Comment by PeterAdam** [comment]
Köszönöm, működik.

Esetleg az XSD validation ablakban vagy az XSD validation result szövegdoboz tetejére lehene írni a következő fájl ellenőrzésének eredményét, vagy törölni futtatás előtt, vagy egy törlés gombot létrehozni? Így első ránézésre ismét sikertelennek mutatja az ellenőrzést, főleg, ha annyi hiba volt benne, hogy a szövegdoboz rögtön betelik?

**Comment by renced42** [comment]
Szia Nyitottam egy új issuet #3 Ott jelzem ha készen van.
Ezt most zárom.
