### ISSUE TITLE
 A queryTaxPayer operáció meghívásakor az alkalmazás figyelmen kívül hagyja a taxpayer taxnumber mező értékét

### ISSUE THREAD

**Issue by tothlp** [nav-gov-hu/Online-Invoice-Test-Tool#2]
A queryTaxPayer operáció meghívásakor az alkalmazás figyelmen kívül hagyja a taxpayer taxnumber mező értékét, és mindig a technikai felhasználó cégadatait adja vissza.

**Comment by renced42** [comment]
Kedves @tothlp 
Köszi a jelzést a következő verzióba javítom.

**Comment by tothlp** [comment]
Köszönöm a gyors választ! :)

**Comment by arnolddozsa** [comment]
Üdv ez még mindig aktuális. Frissen telepítettem és a lekérdező adószámát kérdezi le.

**Comment by renced42** [comment]
Kedves @arnolddozsa 

Igen, a "hiba" kiküszöbölhető, ha a Request ablakban az utolsó taxNumber értékét átírod arra amire szeretnéd a lekérdezést futtatni.
