### ISSUE TITLE
Creating a test account

### ISSUE THREAD

**Issue by rstrajher** [nav-gov-hu/Online-Invoice-Test-Tool#5]
Hi,

my company is an EDI provider and some of our customers gave us a request to give them the ability to send invoices to Online Invoicing System.
For testing purposes, we'd like to create a test account in your system for our company and once we're production ready, we'll instruct our customers to get their own production accounts.

Can you please tell me how can we get the test account? I've sent a message through the official web form last week, but didn't get an answer yet.

Thank you very much.

Robert

**Comment by renced42** [comment]
Dear @rstrajher 

You can find information here https://onlineszamla.nav.gov.hu/tajekoztatas_a_regisztraciorol (Change page language to english)
