### ISSUE TITLE
Online Invoice Test Tool Build: 3.0 ... dirindex hiba 

### ISSUE THREAD

**Issue by robozb** [nav-gov-hu/Online-Invoice-Test-Tool#6]
Kedves Közösség!

Ezzel mit lehet kezdeni?

2021.03.09 13:21:02:4758 .dirindex file doesn't exist!

Köszönöm szépen!

**Comment by renced42** [comment]
Kedves @robozb 

Alapesetben nem kell foglalkozni vele, a program keres bizonyos helyeken (ott ahonnan fel kell olvasnia az állomány listát) ilyen állományt ha nem találja akkor írja ki.

**Comment by robozb** [comment]
OK, köszönöm szépen!

**Comment by robozb** [comment]
szűz telepítésnél is felmerül a probléma

**Comment by renced42** [comment]
Igen ez teljesen normális, hiszen akkor még nincs ott semmi. Az majd használat közben jön létre.

**Comment by robozb** [comment]
OK, köszönöm, értem!
