### ISSUE TITLE
Online Invoice Test Tool használata számla beküldéshez.

### ISSUE THREAD

**Issue by PixelCM** [nav-gov-hu/Online-Invoice-Test-Tool#9]
Sziasztok! 

A webshopunk által rendeléskor automatikusan generált számlából generálnánk egy XML-t a "Belfoldi termekertekesites maganszemelynek" mintaszámlátok alapján. 
Ezek után a számlát már nem kézi rögzítéssel jelentenénk be, hanem az Online Invoice Test Tool-on keresztül. A számlából generált XML tartalmát bemásolnánk a program XML data ablakába, majd a Log ablakban lévő zöld nyilas boríték ikonra kattintva küldenénk el?! 
Működhet ez az elgondolás?
A Miscellaneous Settingsben nem a test API-t, hanem az éles rendszert állítanánk be. 
Ezen kívül van más beállítás amit eszközölnünk kellene a programban, hogy megfelelően működjön a célunknak megfelelően?

Válaszotokat előre is köszönöm!

Üdv. Ákos

**Comment by PixelCM** [comment]
Sziasztok!

Lassan egy hónap elteltével nem tudnátok válaszolni?

Köszi előre is!

**Comment by renced42** [comment]
Kedves @PixelCM 

Bocs a késői válaszért de inkább később mint soha :)
Szóval a programra nincs support arra, használod amire szeretnéd, de felhívom a figyelmet a felhasználási feltételekre.
